# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
files: ^backend/
repos:
  - repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
      - id: black
        language_version: python3.9
  - repo: https://github.com/pycqa/flake8
    rev: "3.9.0"
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: mixed-line-ending
        args:
          - "--fix=lf"
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
        name: isort (python)
      - id: isort
        args: ["--profile", "black"]
        name: isort (cython)
      - id: isort
        args: ["--profile", "black"]
        name: isort (pyi)
        types: [pyi]
