version: "3.1"
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    container_name: pv_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: powervision
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile.api
    restart: always
    depends_on:
      - db
    ports:
      - 3000:3000
    container_name: pv_api
    environment:
      POSTGRES_HOST: host.docker.internal # change this to 172.17.0.1 if linux os
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DATABASE: powervision
      PORT: 3000
      MODE: DEV
      RUN_MIGRATIONS: true
  site:
    restart: always
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.site
      args:
        VITE_API_URL: localhost # Change this to IP of API server if running remote
    depends_on:
      - db
      - api
    ports:
      - 4173:4173
      - 5173:5173
    container_name: pv_site
