"""update device

Revision ID: 49bd95f4b5a7
Revises: 3f124bde3c55
Create Date: 2025-01-19 22:02:01.627400

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "49bd95f4b5a7"
down_revision: Union[str, None] = "3f124bde3c55"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "device",
        "account_id",
        existing_type=sa.TEXT(),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.create_foreign_key(None, "device", "accounts", ["account_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "device", type_="foreignkey")
    op.alter_column(
        "device",
        "account_id",
        existing_type=sa.Integer(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
