"""update accounts

Revision ID: 50e8ad3b8021
Revises: 5733e2260543
Create Date: 2025-01-19 21:52:23.771361

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "50e8ad3b8021"
down_revision: Union[str, None] = "5733e2260543"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("accounts", sa.Column("name", sa.Text(), nullable=True))
    op.add_column("accounts", sa.Column("password", sa.Text(), nullable=True))
    op.add_column(
        "accounts",
        sa.Column(
            "dt_updated", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "dt_updated")
    op.drop_column("accounts", "password")
    op.drop_column("accounts", "name")
    # ### end Alembic commands ###
