"""add battery type table

Revision ID: 8b238966b387
Revises: b654b0407a24
Create Date: 2025-01-19 23:11:46.792110

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8b238966b387"
down_revision: Union[str, None] = "b654b0407a24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "battery_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column(
            "dt_updated", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("device", sa.Column("battery_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "device", "battery_type", ["battery_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "device", type_="foreignkey")
    op.drop_column("device", "battery_id")
    op.drop_table("battery_type")
    # ### end Alembic commands ###
