"""add charging table

Revision ID: b654b0407a24
Revises: 0c59e5564ebc
Create Date: 2025-01-19 23:06:46.090421

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b654b0407a24"
down_revision: Union[str, None] = "0c59e5564ebc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "powervisiony_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=True),
        sa.Column("powervisiony_level", sa.Float(), nullable=True),
        sa.Column("number_charges", sa.Integer(), nullable=True),
        sa.Column(
            "dt_updated", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["device.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "charging",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=True),
        sa.Column(
            "last_charged",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("depletion_date", sa.Date(), nullable=True),
        sa.Column(
            "dt_updated", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["device.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("powervisionyStatus")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "powervisionyStatus",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "powervisiony_levl",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("number_charges", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "dt_updated",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["device_id"], ["device.id"], name="powervisionyStatus_device_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="powervisionyStatus_pkey"),
    )
    op.drop_table("charging")
    op.drop_table("powervisiony_status")
    # ### end Alembic commands ###
