"""fix batteryid typo

Revision ID: dbe7a7d69816
Revises: 8682229ce916
Create Date: 2025-01-20 18:28:36.246257

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dbe7a7d69816"
down_revision: Union[str, None] = "8682229ce916"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("device", sa.Column("battery_id", sa.Integer(), nullable=True))
    op.drop_constraint("device_batteryid_fkey", "device", type_="foreignkey")
    op.create_foreign_key(None, "device", "battery_type", ["battery_id"], ["id"])
    op.drop_column("device", "batteryid")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "device",
        sa.Column("batteryid", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "device", type_="foreignkey")
    op.create_foreign_key(
        "device_batteryid_fkey", "device", "battery_type", ["batteryid"], ["id"]
    )
    op.drop_column("device", "battery_id")
    # ### end Alembic commands ###
